[buildPlans.IosevkaGaussfff]
family = "Iosevka Gaussfff"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaGaussfff.variants.design]
one = "line"
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "open-serifless"
five = "oblique-flat-serifless"
six = "straight-bar"
seven = "straight-serifless-crossbar"
eight = "crossing"
nine = "straight-bar"
zero = "dotted"
capital-a = "round-top-serifless"
capital-b = "more-asymmetric-interrupted-serifless"
capital-c = "bilateral-inward-serifed"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothed-inward-serifed-capped"
capital-h = "serifless"
capital-i = "short-serifed"
capital-j = "serifed"
capital-k = "symmetric-connected-serifless"
capital-l = "serifless"
capital-m = "slanted-sides-hanging-serifless"
capital-n = "asymmetric-serifless"
capital-p = "open-serifless"
capital-q = "vertical-crossing"
capital-r = "straight-serifless"
capital-s = "unilateral-inward-serifed"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-w = "straight-double-v-serifless"
capital-x = "straight-bilateral-motion-serifed"
capital-y = "straight-serifless"
capital-z = "curly-serifless-with-crossbar"
a = "single-storey-top-cut-serifless"
b = "toothless-corner-serifless"
c = "unilateral-inward-serifed"
d = "toothless-corner-serifless"
e = "rounded"
f = "flat-hook-diagonal-tailed-crossbar-at-x-height"
g = "double-storey-open"
h = "straight-serifless"
i = "serifed-diagonal-tailed"
j = "diagonal-tailed-serifed"
k = "symmetric-connected-serifless"
l = "serifed-diagonal-tailed"
m = "earless-corner-double-arch-short-leg-serifless"
n = "earless-rounded-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-diagonal-tailed-serifless"
r = "compact-serifless"
s = "bilateral-inward-serifed"
t = "diagonal-tailed-short-neck2"
u = "toothed-serifless"
v = "cursive-serifless"
w = "straight-double-v-serifless"
x = "semi-chancery-straight-serifless"
y = "straight-serifless"
z = "curly-serifless-with-crossbar"
capital-eszet = "flat-top-serifless"
long-s = "flat-hook-diagonal-tailed"
eszet = "longs-s-lig-serifless"
lower-eth = "straight-bar"
capital-thorn = "serifless"
lower-thorn = "serifless"
lower-alpha = "crossing"
lower-beta = "standard"
capital-gamma = "serifless"
lower-gamma = "casual"
capital-delta = "straight"
lower-delta = "flat-top"
lower-eta = "serifless"
lower-theta = "diamond"
lower-iota = "diagonal-tailed"
lower-kappa = "symmetric-connected-serifless"
capital-lambda = "straight-serifless"
lower-lambda = "tailed-turn"
lower-mu = "toothed-serifless"
lower-nu = "casual"
lower-xi = "rounded"
lower-pi = "tailed"
lower-tau = "diagonal-tailed"
lower-upsilon = "casual-serifless"
lower-phi = "cursive"
lower-chi = "semi-chancery-straight-serifless"
lower-psi = "serifless"
partial-derivative = "straight-bar"
cyrl-a = "single-storey-tailed"
cyrl-ve = "standard-interrupted-serifless"
cyrl-capital-zhe = "symmetric-connected"
cyrl-zhe = "symmetric-connected"
cyrl-capital-ze = "unilateral-inward-serifed"
cyrl-ze = "unilateral-inward-serifed"
cyrl-capital-ka = "curly-serifless"
cyrl-ka = "curly-serifless"
cyrl-el = "straight"
cyrl-em = "slanted-sides-flat-bottom-serifless"
cyrl-capital-en = "serifless"
cyrl-en = "serifless"
cyrl-capital-er = "open-serifless"
cyrl-er = "earless-corner-serifless"
cyrl-capital-u = "straight-serifless"
cyrl-u = "straight-serifless"
cyrl-ef = "split-diagonal-tailed-cursive"
cyrl-che = "standard"
cyrl-yeri = "cursive"
cyrl-yery = "cursive"
cyrl-capital-e = "unilateral-inward-serifed"
cyrl-e = "unilateral-inward-serifed"
cyrl-capital-ya = "straight-open-serifless"
cyrl-ya = "straight-open-serifless"
tittle = "round"
diacritic-dot = "round"
punctuation-dot = "round"
braille-dot = "round"
tilde = "low"
asterisk = "turn-penta-high"
underscore = "low"
caret = "high"
ascii-grave = "raised-turn-comma"
ascii-single-quote = "straight"
paren = "flat-arc"
brace = "curly-flat-boundary"
guillemet = "straight"
number-sign = "upright-open-tall"
ampersand = "et-toothless-rounded"
at = "threefold-solid-inner-tall"
dollar = "interrupted-cap"
cent = "bar-interrupted-cap"
percent = "dots"
bar = "force-upright"
question = "corner-flat-hooked"
pilcrow = "curved"
micro-sign = "toothed-serifless"
decorative-angle-brackets = "tall"
lig-ltgteq = "slanted"
lig-neq = "more-slanted-dotted"
lig-equal-chain = "with-notch"
lig-hyphen-chain = "with-notch"
lig-plus-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

  [buildPlans.IosevkaGaussfff.ligations]
  inherits = "swift"

[buildPlans.IosevkaGaussfff.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaGaussfff.weights.Bold]
shape = 700
menu = 700
css = 700
